### ISSUE TITLE
Appraisal of Ultimate Flask Front End

### ISSUE THREAD

**Issue by pigeonflight** [realpython/ultimate-flask-front-end#1]
Just curious, what makes this the Ultimate Flask Front End?
(Wasn't sure where else to put this comment.)

**Comment by mjhea0** [comment]
haha. you can comment on the blog post -> https://realpython.com/blog/python/the-ultimate-flask-front-end/

**Comment by pigeonflight** [comment]
Thanks... that post gives some context.
